# Basic site configuration
baseurl = "http://www.ece3sat.com/"
languageCode = "en-us"
theme = "ece3sat"
title = "ECE3SAT"
canonifyURLs = true

# Supplementary features
enableGitInfo = true
enableEmoji = true
